POST http://localhost:5286/breakfasts
Content-Type: application/json

{
    "name": "V1321321321",
    "description": "V1321321321 V1321321321 V1321321321 V1321321321 V1321321321 V1321321321",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}